### ISSUE TITLE
Posting photo work?

### ISSUE THREAD

**Issue by 1nSaneRu** [michelmelo/instagram-private-api#1]
After nov 2019 MGP25 library doen't post media. But I see that many softwares work now...
Posting work in this fork?

**Comment by michelmelo** [comment]
Hello yes. This is a clone of MGP25 and the media post is working. @1nSaneRu

**Comment by michelmelo** [comment]
leave an example here that is not working and I make an example of mine working.

**Comment by 1nSaneRu** [comment]
`<?php
...
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);

try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Login stage: Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

if($post_type == "photo"){
try {
    $photo = new \InstagramAPI\Media\Photo\InstagramPhoto($photoFilename);
    $response = $ig->timeline->uploadPhoto($photo->getFile(), ['caption' => "text"]);
    $media = $response->getMedia();
    $id = $media->getId();
    $code = $media->getCode();
    $url = "https://www.instagram.com/p/".$code."/";
} catch (\Exception $e) {
    echo 'Photo stage: Something went wrong: '.$e->getMessage()."\n";
}
}
if($post_type == "album"){
try {
    $response = $ig->timeline->uploadAlbum($media, ['caption' => $captionText]);
    $media = $response->getMedia();
    $id = $media->getId();
    $code = $media->getCode();
    $url = "https://www.instagram.com/p/".$code."/";
} catch (\Exception $e) {
    echo 'ALBUM stage: Something went wrong: '.$e->getMessage()."\n";
}}}
?>`

But I get:
> ^[[1;34mPOST:  ^[[0mhttps://i.instagram.com/api/v1/upload/photo/
^[[1;33m→ 345.72kB^[[0m
^[[0;32m← 400    58B^[[0m
^[[0;36mRESPONSE: ^[[0mSomething is wrong. Please check your input and try again.

ALBUM stage: Something went wrong: Invalid request options.

**Comment by 1nSaneRu** [comment]
https://github.com/brunocvcunha/instagram4j/pull/411 - on Java developer fix this problem. My skills to small for it :(

**Comment by michelmelo** [comment]
I'm testing .. I already solve this problem

**Comment by 1nSaneRu** [comment]
How/when I get update? I try to use 1.13.18 and not working...

**Comment by michelmelo** [comment]
@1nSaneRu can test branh develop?

**Comment by 1nSaneRu** [comment]
Yes, it's work. But you change path for "sessions" folder ;) It's not a problem

**Comment by michelmelo** [comment]
done
