### ISSUE TITLE
Close repository

### ISSUE THREAD

**Issue by mgp25** [michelmelo/instagram-private-api#11]
Hello,

Due to legal reasons, I am asking you to close this repository, if not I will contact Github so they will close it

Bets regards

**Comment by michelmelo** [comment]
@mgp25 What is the reason for me to close? as is several other ... repositories. I am continuing what you started doing, and stopped.

**Comment by mgp25** [comment]
@michelmelo you ripped of my code, deleted the authors, violating license and copyrighted code and further more, publishing a code that is under a DCMA. Just contacted Github.

Regards

**Comment by michelmelo** [comment]
@mgp25 if you see the composer this is your name. 
where your name as an author is kept.

**Comment by mgp25** [comment]
You are still violating the rest

**Comment by michelmelo** [comment]
@mgp25 
to several other repositories with your code, and others much more modified and removed your name. At least that I am maintaining. Out of respect for your work. and I'm keeping it up to date.
You blocked me from replying in your repository.
it's a shame to see that.
