### ISSUE TITLE
live broadcast list

### ISSUE THREAD

**Issue by irdeveloper89** [michelmelo/instagram-private-api#6]
I want to get all followers/following the live broadcast list with broadcast  URL  like stories

**Comment by irdeveloper89** [comment]
do you have any idea for this ?

**Comment by michelmelo** [comment]
getting all followers and followers in a row is possible. the lives you can see the urls

https://github.com/michelmelo/instagram-private-api/blob/master/wiki/People.md
https://github.com/michelmelo/instagram-private-api/blob/master/wiki/Live.md
