### ISSUE TITLE
get all feeds

### ISSUE THREAD

**Issue by irdeveloper89** [michelmelo/instagram-private-api#7]
how I can get the suggested posts, I mean the post that appears when I click on the search icon. and not timeline

**Comment by michelmelo** [comment]
Discover new people via Facebook's algorithm. This matches you with other people using multiple algorithms such as "friends of friends", "location", "people using similar hashtags", etc.
`$ig->people->discoverPeople();`

**Comment by irdeveloper89** [comment]
Thnks but I need this 

https://pasteboard.co/IVe6N05.jpg

How I can get this api

**Comment by michelmelo** [comment]
We are still in an older version. so don't see all the information.

**Comment by irdeveloper89** [comment]
> 
> 
> We are still in an older version. so don't see all the information.

Do you know when this will be added?

**Comment by michelmelo** [comment]
in this version that is the code today, I can't. I have to change more things @irdeveloper89
